name: Check the answer to the exercise
on:
  issue_comment:
    types: [created]
jobs:
  check-answer:
    if: contains(github.event.issue.labels.*.name, 'exec:matrix-det')
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      COMMENT_ID: ${{ github.event.comment.id }}
      REPO: ${{ github.repository }}
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Get answer
        id: get-answer
        run: |
          echo "ANSWER=$(grep -oP "(?<=<summary>Answer</summary><p>).*(?=</p>)" <<< $ISSUE_BODY)" >> "$GITHUB_OUTPUT"
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
      - name: The answer is not correct
        if: steps.get-answer.outputs.ANSWER != github.event.comment.body
        run: |
          curl -X POST -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO/issues/comments/$COMMENT_ID/reactions" \
            -d '{"content": "-1"}'
      - name: The answer is correct
        if: steps.get-answer.outputs.ANSWER == github.event.comment.body
        run: |
          curl -X POST -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO/issues/comments/$COMMENT_ID/reactions" \
            -d '{"content": "hooray"}'
          gh issue close $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
