name: Create an exercise to find the determinant of a matrix
on:
  issues:
    types: [opened]
jobs:
  add-comment:
    if: contains(github.event.issue.labels.*.name, 'matrix det')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
      - name: Generate exercise
        run: |
          gh issue edit "$NUMBER" -t "$TITLE" -b "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          TITLE: Matrix Determinant ${{ github.event.issue.created_at }}
          BODY: $(python scripts/exec_matrix_det.py)
