name: Create an exercise to find the determinant of a matrix
on:
  issues:
    types: [opened]
jobs:
  add-comment:
    if: github.event.issue.title == 'matrix det'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create exercise
        run: echo ${{ github.event.issue.title }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
              This my first action!
