name: Create an exercise to find the determinant of a matrix
on:
  issues:
    types: [opened]
jobs:
  add-comment:
    if: contains(github.event.issue.labels.*.name, 'matrix det')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create exercise
        run: gh issue edit "$NUMBER" -t "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: Matrix Determinant ${{ github.event.issue.created_at }}
