name: Create an exercise to find the determinant of a matrix
on:
  issues:
    types: [opened]
jobs:
  exec-matrix-det:
    if: contains(github.event.issue.labels.*.name, 'exec:matrix-det')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
      - name: Generate exercise
        id: generate-exercise
        run: |
          {
            echo 'EXERCISE_TEXT<<EOF'
            python scripts/exec_matrix_det.py "$DIFFICULTY"
            echo EOF
          } >> "$GITHUB_OUTPUT"
        env:
          DIFFICULTY:
            ${{ contains(github.event.issue.labels.*.name, 'difficulty:easy') && 'easy' || contains(github.event.issue.labels.*.name, 'difficulty:medium') && 'medium' || 'hard' }}
      - name: Update issue
        run: |
          gh issue edit "$NUMBER" \
            -t "$TITLE" \
            -b "$EXERCISE_TEXT" \
            --add-assignee "$ASSIGNEE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          TITLE: Matrix Determinant ${{ github.event.issue.created_at }}
          EXERCISE_TEXT: ${{ steps.generate-exercise.outputs.EXERCISE_TEXT }}
          ASSIGNEE: ${{ github.repository_owner }}
